# Generated by Django 3.2.9 on 2021-11-28 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 17, 30, 46, 950303)),
        ),
    ]
