# Generated by Django 3.2.9 on 2021-11-28 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 17, 32, 54, 807841, tzinfo=utc)),
        ),
    ]
